version: '3.8'

services:
  postgres-demo7:
    image: postgres:17-alpine
    container_name: postgres-demo7
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data_demo7:/var/lib/postgresql/data
  
  swagger-demo7:
    image: swaggerapi/swagger-ui
    container_name: swagger-demo7
    ports:
      - "8085:8080"
    environment:
      - SWAGGER_JSON=/api/api.yaml
    volumes:
      - ./api.yaml:/api/api.yaml

volumes:
  postgres_data_demo7: